# coding: utf-8

# flake8: noqa
from __future__ import absolute_import
# import models into model package
from swagger_server.models.animal_properties import AnimalProperties
from swagger_server.models.anpr_event import AnprEvent
from swagger_server.models.anpr_events_response import AnprEventsResponse
from swagger_server.models.attribute_event import AttributeEvent
from swagger_server.models.attribute_events_response import AttributeEventsResponse
from swagger_server.models.capability import Capability
from swagger_server.models.clip import Clip
from swagger_server.models.clips_response import ClipsResponse
from swagger_server.models.color import Color
from swagger_server.models.config import Config
from swagger_server.models.default_response import DefaultResponse
from swagger_server.models.destination_end_point import DestinationEndPoint
from swagger_server.models.destination_end_point_destination_list import DestinationEndPointDestinationList
from swagger_server.models.destination_type import DestinationType
from swagger_server.models.engine import Engine
from swagger_server.models.engine_task import EngineTask
from swagger_server.models.engine_task_line_setting import EngineTaskLineSetting
from swagger_server.models.engine_task_zone_setting import EngineTaskZoneSetting
from swagger_server.models.engine_tasks_response import EngineTasksResponse
from swagger_server.models.engines_response import EnginesResponse
from swagger_server.models.event import Event
from swagger_server.models.event_details import EventDetails
from swagger_server.models.event_snaps_response import EventSnapsResponse
from swagger_server.models.event_type import EventType
from swagger_server.models.evidence_config import EvidenceConfig
from swagger_server.models.extra import Extra
from swagger_server.models.href import Href
from swagger_server.models.human_properties import HumanProperties
from swagger_server.models.line import Line
from swagger_server.models.line_type import LineType
from swagger_server.models.links import Links
from swagger_server.models.links_self import LinksSelf
from swagger_server.models.links_self_self import LinksSelfSelf
from swagger_server.models.meta import Meta
from swagger_server.models.meta_anpr_event import MetaAnprEvent
from swagger_server.models.meta_attribute_event import MetaAttributeEvent
from swagger_server.models.meta_va_event import MetaVaEvent
from swagger_server.models.object_dimension import ObjectDimension
from swagger_server.models.object_direct_properties import ObjectDirectProperties
from swagger_server.models.object_indirect_properties import ObjectIndirectProperties
from swagger_server.models.object_info import ObjectInfo
from swagger_server.models.object_rect import ObjectRect
from swagger_server.models.schedule_source import ScheduleSource
from swagger_server.models.snap import Snap
from swagger_server.models.snaps_response import SnapsResponse
from swagger_server.models.source_end_point import SourceEndPoint
from swagger_server.models.source_end_point_source_list import SourceEndPointSourceList
from swagger_server.models.source_type import SourceType
from swagger_server.models.title import Title
from swagger_server.models.track_properties import TrackProperties
from swagger_server.models.va_event import VaEvent
from swagger_server.models.va_events_response import VaEventsResponse
from swagger_server.models.vehicle_properties import VehicleProperties
from swagger_server.models.vehicle_type import VehicleType
from swagger_server.models.vertex import Vertex
from swagger_server.models.vtpl_video_frame import VtplVideoFrame
from swagger_server.models.zone import Zone
from swagger_server.models.zone_type import ZoneType
