# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AnimalProperties(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, color: str=None):  # noqa: E501
        """AnimalProperties - a model defined in Swagger

        :param color: The color of this AnimalProperties.  # noqa: E501
        :type color: str
        """
        self.swagger_types = {
            'color': str
        }

        self.attribute_map = {
            'color': 'color'
        }
        self._color = color

    @classmethod
    def from_dict(cls, dikt) -> 'AnimalProperties':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The animalProperties of this AnimalProperties.  # noqa: E501
        :rtype: AnimalProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def color(self) -> str:
        """Gets the color of this AnimalProperties.


        :return: The color of this AnimalProperties.
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color: str):
        """Sets the color of this AnimalProperties.


        :param color: The color of this AnimalProperties.
        :type color: str
        """

        self._color = color
