# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Capability(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    _201 = "201"
    _206 = "206"
    _207 = "207"
    _210 = "210"
    _211 = "211"
    _221 = "221"
    _222 = "222"
    _260 = "260"
    _261 = "261"
    _322 = "322"
    _324 = "324"
    _325 = "325"
    _329 = "329"
    _330 = "330"
    _315 = "315"
    _331 = "331"
    _2201 = "2201"
    def __init__(self):  # noqa: E501
        """Capability - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Capability':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The capability of this Capability.  # noqa: E501
        :rtype: Capability
        """
        return util.deserialize_model(dikt, cls)
