# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Color(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    BLACK = "Black"
    BLUE = "Blue"
    CYAN = "Cyan"
    GRAY = "Gray"
    GREEN = "Green"
    PURPLE = "Purple"
    RED = "Red"
    YELLOW = "Yellow"
    SILVER = "Silver"
    GOLD = "Gold"
    WHITE = "White"
    UNDETERMINED = "Undetermined"
    OTHER = "Other"
    def __init__(self):  # noqa: E501
        """Color - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Color':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The color of this Color.  # noqa: E501
        :rtype: Color
        """
        return util.deserialize_model(dikt, cls)
