# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.destination_type import DestinationType  # noqa: F401,E501
from swagger_server import util


class DestinationEndPointDestinationList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, source_id: str=None, type: DestinationType=None, base_url: str=None, name: str=None, user: str=None, _pass: str=None):  # noqa: E501
        """DestinationEndPointDestinationList - a model defined in Swagger

        :param source_id: The source_id of this DestinationEndPointDestinationList.  # noqa: E501
        :type source_id: str
        :param type: The type of this DestinationEndPointDestinationList.  # noqa: E501
        :type type: DestinationType
        :param base_url: The base_url of this DestinationEndPointDestinationList.  # noqa: E501
        :type base_url: str
        :param name: The name of this DestinationEndPointDestinationList.  # noqa: E501
        :type name: str
        :param user: The user of this DestinationEndPointDestinationList.  # noqa: E501
        :type user: str
        :param _pass: The _pass of this DestinationEndPointDestinationList.  # noqa: E501
        :type _pass: str
        """
        self.swagger_types = {
            'source_id': str,
            'type': DestinationType,
            'base_url': str,
            'name': str,
            'user': str,
            '_pass': str
        }

        self.attribute_map = {
            'source_id': 'sourceId',
            'type': 'type',
            'base_url': 'baseUrl',
            'name': 'name',
            'user': 'user',
            '_pass': 'pass'
        }
        self._source_id = source_id
        self._type = type
        self._base_url = base_url
        self._name = name
        self._user = user
        self.__pass = _pass

    @classmethod
    def from_dict(cls, dikt) -> 'DestinationEndPointDestinationList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The destinationEndPoint_destinationList of this DestinationEndPointDestinationList.  # noqa: E501
        :rtype: DestinationEndPointDestinationList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_id(self) -> str:
        """Gets the source_id of this DestinationEndPointDestinationList.


        :return: The source_id of this DestinationEndPointDestinationList.
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id: str):
        """Sets the source_id of this DestinationEndPointDestinationList.


        :param source_id: The source_id of this DestinationEndPointDestinationList.
        :type source_id: str
        """

        self._source_id = source_id

    @property
    def type(self) -> DestinationType:
        """Gets the type of this DestinationEndPointDestinationList.


        :return: The type of this DestinationEndPointDestinationList.
        :rtype: DestinationType
        """
        return self._type

    @type.setter
    def type(self, type: DestinationType):
        """Sets the type of this DestinationEndPointDestinationList.


        :param type: The type of this DestinationEndPointDestinationList.
        :type type: DestinationType
        """

        self._type = type

    @property
    def base_url(self) -> str:
        """Gets the base_url of this DestinationEndPointDestinationList.


        :return: The base_url of this DestinationEndPointDestinationList.
        :rtype: str
        """
        return self._base_url

    @base_url.setter
    def base_url(self, base_url: str):
        """Sets the base_url of this DestinationEndPointDestinationList.


        :param base_url: The base_url of this DestinationEndPointDestinationList.
        :type base_url: str
        """

        self._base_url = base_url

    @property
    def name(self) -> str:
        """Gets the name of this DestinationEndPointDestinationList.


        :return: The name of this DestinationEndPointDestinationList.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DestinationEndPointDestinationList.


        :param name: The name of this DestinationEndPointDestinationList.
        :type name: str
        """

        self._name = name

    @property
    def user(self) -> str:
        """Gets the user of this DestinationEndPointDestinationList.


        :return: The user of this DestinationEndPointDestinationList.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this DestinationEndPointDestinationList.


        :param user: The user of this DestinationEndPointDestinationList.
        :type user: str
        """

        self._user = user

    @property
    def _pass(self) -> str:
        """Gets the _pass of this DestinationEndPointDestinationList.


        :return: The _pass of this DestinationEndPointDestinationList.
        :rtype: str
        """
        return self.__pass

    @_pass.setter
    def _pass(self, _pass: str):
        """Sets the _pass of this DestinationEndPointDestinationList.


        :param _pass: The _pass of this DestinationEndPointDestinationList.
        :type _pass: str
        """

        self.__pass = _pass
