# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.destination_end_point_destination_list import DestinationEndPointDestinationList  # noqa: F401,E501
from swagger_server.models.extra import Extra  # noqa: F401,E501
from swagger_server import util


class DestinationEndPoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, destination_list: List[DestinationEndPointDestinationList]=None, extras: List[Extra]=None):  # noqa: E501
        """DestinationEndPoint - a model defined in Swagger

        :param destination_list: The destination_list of this DestinationEndPoint.  # noqa: E501
        :type destination_list: List[DestinationEndPointDestinationList]
        :param extras: The extras of this DestinationEndPoint.  # noqa: E501
        :type extras: List[Extra]
        """
        self.swagger_types = {
            'destination_list': List[DestinationEndPointDestinationList],
            'extras': List[Extra]
        }

        self.attribute_map = {
            'destination_list': 'destinationList',
            'extras': 'extras'
        }
        self._destination_list = destination_list
        self._extras = extras

    @classmethod
    def from_dict(cls, dikt) -> 'DestinationEndPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The destinationEndPoint of this DestinationEndPoint.  # noqa: E501
        :rtype: DestinationEndPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def destination_list(self) -> List[DestinationEndPointDestinationList]:
        """Gets the destination_list of this DestinationEndPoint.


        :return: The destination_list of this DestinationEndPoint.
        :rtype: List[DestinationEndPointDestinationList]
        """
        return self._destination_list

    @destination_list.setter
    def destination_list(self, destination_list: List[DestinationEndPointDestinationList]):
        """Sets the destination_list of this DestinationEndPoint.


        :param destination_list: The destination_list of this DestinationEndPoint.
        :type destination_list: List[DestinationEndPointDestinationList]
        """

        self._destination_list = destination_list

    @property
    def extras(self) -> List[Extra]:
        """Gets the extras of this DestinationEndPoint.


        :return: The extras of this DestinationEndPoint.
        :rtype: List[Extra]
        """
        return self._extras

    @extras.setter
    def extras(self, extras: List[Extra]):
        """Sets the extras of this DestinationEndPoint.


        :param extras: The extras of this DestinationEndPoint.
        :type extras: List[Extra]
        """

        self._extras = extras
