# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.line import Line  # noqa: F401,E501
from swagger_server import util


class EngineTaskLineSetting(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reference_width: int=None, reference_height: int=None, lines: List[Line]=None):  # noqa: E501
        """EngineTaskLineSetting - a model defined in Swagger

        :param reference_width: The reference_width of this EngineTaskLineSetting.  # noqa: E501
        :type reference_width: int
        :param reference_height: The reference_height of this EngineTaskLineSetting.  # noqa: E501
        :type reference_height: int
        :param lines: The lines of this EngineTaskLineSetting.  # noqa: E501
        :type lines: List[Line]
        """
        self.swagger_types = {
            'reference_width': int,
            'reference_height': int,
            'lines': List[Line]
        }

        self.attribute_map = {
            'reference_width': 'referenceWidth',
            'reference_height': 'referenceHeight',
            'lines': 'lines'
        }
        self._reference_width = reference_width
        self._reference_height = reference_height
        self._lines = lines

    @classmethod
    def from_dict(cls, dikt) -> 'EngineTaskLineSetting':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The engineTask_lineSetting of this EngineTaskLineSetting.  # noqa: E501
        :rtype: EngineTaskLineSetting
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reference_width(self) -> int:
        """Gets the reference_width of this EngineTaskLineSetting.

        Reference width on which zones are relevent  # noqa: E501

        :return: The reference_width of this EngineTaskLineSetting.
        :rtype: int
        """
        return self._reference_width

    @reference_width.setter
    def reference_width(self, reference_width: int):
        """Sets the reference_width of this EngineTaskLineSetting.

        Reference width on which zones are relevent  # noqa: E501

        :param reference_width: The reference_width of this EngineTaskLineSetting.
        :type reference_width: int
        """

        self._reference_width = reference_width

    @property
    def reference_height(self) -> int:
        """Gets the reference_height of this EngineTaskLineSetting.

        Reference height on which zones are relevent  # noqa: E501

        :return: The reference_height of this EngineTaskLineSetting.
        :rtype: int
        """
        return self._reference_height

    @reference_height.setter
    def reference_height(self, reference_height: int):
        """Sets the reference_height of this EngineTaskLineSetting.

        Reference height on which zones are relevent  # noqa: E501

        :param reference_height: The reference_height of this EngineTaskLineSetting.
        :type reference_height: int
        """

        self._reference_height = reference_height

    @property
    def lines(self) -> List[Line]:
        """Gets the lines of this EngineTaskLineSetting.


        :return: The lines of this EngineTaskLineSetting.
        :rtype: List[Line]
        """
        return self._lines

    @lines.setter
    def lines(self, lines: List[Line]):
        """Sets the lines of this EngineTaskLineSetting.


        :param lines: The lines of this EngineTaskLineSetting.
        :type lines: List[Line]
        """

        self._lines = lines
