# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.zone import Zone  # noqa: F401,E501
from swagger_server import util


class EngineTaskZoneSetting(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reference_width: int=None, reference_height: int=None, zones: List[Zone]=None):  # noqa: E501
        """EngineTaskZoneSetting - a model defined in Swagger

        :param reference_width: The reference_width of this EngineTaskZoneSetting.  # noqa: E501
        :type reference_width: int
        :param reference_height: The reference_height of this EngineTaskZoneSetting.  # noqa: E501
        :type reference_height: int
        :param zones: The zones of this EngineTaskZoneSetting.  # noqa: E501
        :type zones: List[Zone]
        """
        self.swagger_types = {
            'reference_width': int,
            'reference_height': int,
            'zones': List[Zone]
        }

        self.attribute_map = {
            'reference_width': 'referenceWidth',
            'reference_height': 'referenceHeight',
            'zones': 'zones'
        }
        self._reference_width = reference_width
        self._reference_height = reference_height
        self._zones = zones

    @classmethod
    def from_dict(cls, dikt) -> 'EngineTaskZoneSetting':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The engineTask_zoneSetting of this EngineTaskZoneSetting.  # noqa: E501
        :rtype: EngineTaskZoneSetting
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reference_width(self) -> int:
        """Gets the reference_width of this EngineTaskZoneSetting.

        Reference width on which zones are relevent  # noqa: E501

        :return: The reference_width of this EngineTaskZoneSetting.
        :rtype: int
        """
        return self._reference_width

    @reference_width.setter
    def reference_width(self, reference_width: int):
        """Sets the reference_width of this EngineTaskZoneSetting.

        Reference width on which zones are relevent  # noqa: E501

        :param reference_width: The reference_width of this EngineTaskZoneSetting.
        :type reference_width: int
        """

        self._reference_width = reference_width

    @property
    def reference_height(self) -> int:
        """Gets the reference_height of this EngineTaskZoneSetting.

        Reference height on which zones are relevent  # noqa: E501

        :return: The reference_height of this EngineTaskZoneSetting.
        :rtype: int
        """
        return self._reference_height

    @reference_height.setter
    def reference_height(self, reference_height: int):
        """Sets the reference_height of this EngineTaskZoneSetting.

        Reference height on which zones are relevent  # noqa: E501

        :param reference_height: The reference_height of this EngineTaskZoneSetting.
        :type reference_height: int
        """

        self._reference_height = reference_height

    @property
    def zones(self) -> List[Zone]:
        """Gets the zones of this EngineTaskZoneSetting.


        :return: The zones of this EngineTaskZoneSetting.
        :rtype: List[Zone]
        """
        return self._zones

    @zones.setter
    def zones(self, zones: List[Zone]):
        """Sets the zones of this EngineTaskZoneSetting.


        :param zones: The zones of this EngineTaskZoneSetting.
        :type zones: List[Zone]
        """

        self._zones = zones
