# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.href import Href  # noqa: F401,E501
from swagger_server.models.title import Title  # noqa: F401,E501
from swagger_server import util


class LinksSelfSelf(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: Title=None, href: Href=None):  # noqa: E501
        """LinksSelfSelf - a model defined in Swagger

        :param title: The title of this LinksSelfSelf.  # noqa: E501
        :type title: Title
        :param href: The href of this LinksSelfSelf.  # noqa: E501
        :type href: Href
        """
        self.swagger_types = {
            'title': Title,
            'href': Href
        }

        self.attribute_map = {
            'title': 'title',
            'href': 'href'
        }
        self._title = title
        self._href = href

    @classmethod
    def from_dict(cls, dikt) -> 'LinksSelfSelf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The linksSelf_self of this LinksSelfSelf.  # noqa: E501
        :rtype: LinksSelfSelf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> Title:
        """Gets the title of this LinksSelfSelf.


        :return: The title of this LinksSelfSelf.
        :rtype: Title
        """
        return self._title

    @title.setter
    def title(self, title: Title):
        """Sets the title of this LinksSelfSelf.


        :param title: The title of this LinksSelfSelf.
        :type title: Title
        """

        self._title = title

    @property
    def href(self) -> Href:
        """Gets the href of this LinksSelfSelf.


        :return: The href of this LinksSelfSelf.
        :rtype: Href
        """
        return self._href

    @href.setter
    def href(self, href: Href):
        """Sets the href of this LinksSelfSelf.


        :param href: The href of this LinksSelfSelf.
        :type href: Href
        """

        self._href = href
