# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links_self_self import LinksSelfSelf  # noqa: F401,E501
from swagger_server import util


class LinksSelf(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _self: LinksSelfSelf=None):  # noqa: E501
        """LinksSelf - a model defined in Swagger

        :param _self: The _self of this LinksSelf.  # noqa: E501
        :type _self: LinksSelfSelf
        """
        self.swagger_types = {
            '_self': LinksSelfSelf
        }

        self.attribute_map = {
            '_self': 'self'
        }
        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'LinksSelf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The linksSelf of this LinksSelf.  # noqa: E501
        :rtype: LinksSelf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> LinksSelfSelf:
        """Gets the _self of this LinksSelf.


        :return: The _self of this LinksSelf.
        :rtype: LinksSelfSelf
        """
        return self.__self

    @_self.setter
    def _self(self, _self: LinksSelfSelf):
        """Sets the _self of this LinksSelf.


        :param _self: The _self of this LinksSelf.
        :type _self: LinksSelfSelf
        """

        self.__self = _self
