# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Meta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, page: int=None, max_results: int=None, total: int=None):  # noqa: E501
        """Meta - a model defined in Swagger

        :param page: The page of this Meta.  # noqa: E501
        :type page: int
        :param max_results: The max_results of this Meta.  # noqa: E501
        :type max_results: int
        :param total: The total of this Meta.  # noqa: E501
        :type total: int
        """
        self.swagger_types = {
            'page': int,
            'max_results': int,
            'total': int
        }

        self.attribute_map = {
            'page': 'page',
            'max_results': 'maxResults',
            'total': 'total'
        }
        self._page = page
        self._max_results = max_results
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'Meta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The meta of this Meta.  # noqa: E501
        :rtype: Meta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> int:
        """Gets the page of this Meta.


        :return: The page of this Meta.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this Meta.


        :param page: The page of this Meta.
        :type page: int
        """

        self._page = page

    @property
    def max_results(self) -> int:
        """Gets the max_results of this Meta.


        :return: The max_results of this Meta.
        :rtype: int
        """
        return self._max_results

    @max_results.setter
    def max_results(self, max_results: int):
        """Sets the max_results of this Meta.


        :param max_results: The max_results of this Meta.
        :type max_results: int
        """

        self._max_results = max_results

    @property
    def total(self) -> int:
        """Gets the total of this Meta.


        :return: The total of this Meta.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this Meta.


        :param total: The total of this Meta.
        :type total: int
        """

        self._total = total
