# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MetaVaEvent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, count: int=0):  # noqa: E501
        """MetaVaEvent - a model defined in Swagger

        :param count: The count of this MetaVaEvent.  # noqa: E501
        :type count: int
        """
        self.swagger_types = {
            'count': int
        }

        self.attribute_map = {
            'count': 'count'
        }
        self._count = count

    @classmethod
    def from_dict(cls, dikt) -> 'MetaVaEvent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The metaVaEvent of this MetaVaEvent.  # noqa: E501
        :rtype: MetaVaEvent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def count(self) -> int:
        """Gets the count of this MetaVaEvent.


        :return: The count of this MetaVaEvent.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this MetaVaEvent.


        :param count: The count of this MetaVaEvent.
        :type count: int
        """

        self._count = count
