# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ObjectDimension(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, height: float=0, width: float=0, length: float=0):  # noqa: E501
        """ObjectDimension - a model defined in Swagger

        :param height: The height of this ObjectDimension.  # noqa: E501
        :type height: float
        :param width: The width of this ObjectDimension.  # noqa: E501
        :type width: float
        :param length: The length of this ObjectDimension.  # noqa: E501
        :type length: float
        """
        self.swagger_types = {
            'height': float,
            'width': float,
            'length': float
        }

        self.attribute_map = {
            'height': 'height',
            'width': 'width',
            'length': 'length'
        }
        self._height = height
        self._width = width
        self._length = length

    @classmethod
    def from_dict(cls, dikt) -> 'ObjectDimension':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The objectDimension of this ObjectDimension.  # noqa: E501
        :rtype: ObjectDimension
        """
        return util.deserialize_model(dikt, cls)

    @property
    def height(self) -> float:
        """Gets the height of this ObjectDimension.


        :return: The height of this ObjectDimension.
        :rtype: float
        """
        return self._height

    @height.setter
    def height(self, height: float):
        """Sets the height of this ObjectDimension.


        :param height: The height of this ObjectDimension.
        :type height: float
        """

        self._height = height

    @property
    def width(self) -> float:
        """Gets the width of this ObjectDimension.


        :return: The width of this ObjectDimension.
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width: float):
        """Sets the width of this ObjectDimension.


        :param width: The width of this ObjectDimension.
        :type width: float
        """

        self._width = width

    @property
    def length(self) -> float:
        """Gets the length of this ObjectDimension.


        :return: The length of this ObjectDimension.
        :rtype: float
        """
        return self._length

    @length.setter
    def length(self, length: float):
        """Sets the length of this ObjectDimension.


        :param length: The length of this ObjectDimension.
        :type length: float
        """

        self._length = length
