# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.source_type import SourceType  # noqa: F401,E501
from swagger_server import util


class SourceEndPointSourceList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, source_id: str=None, type: SourceType=None, base_url: str=None, user: str=None, _pass: str=None):  # noqa: E501
        """SourceEndPointSourceList - a model defined in Swagger

        :param source_id: The source_id of this SourceEndPointSourceList.  # noqa: E501
        :type source_id: str
        :param type: The type of this SourceEndPointSourceList.  # noqa: E501
        :type type: SourceType
        :param base_url: The base_url of this SourceEndPointSourceList.  # noqa: E501
        :type base_url: str
        :param user: The user of this SourceEndPointSourceList.  # noqa: E501
        :type user: str
        :param _pass: The _pass of this SourceEndPointSourceList.  # noqa: E501
        :type _pass: str
        """
        self.swagger_types = {
            'source_id': str,
            'type': SourceType,
            'base_url': str,
            'user': str,
            '_pass': str
        }

        self.attribute_map = {
            'source_id': 'sourceId',
            'type': 'type',
            'base_url': 'baseUrl',
            'user': 'user',
            '_pass': 'pass'
        }
        self._source_id = source_id
        self._type = type
        self._base_url = base_url
        self._user = user
        self.__pass = _pass

    @classmethod
    def from_dict(cls, dikt) -> 'SourceEndPointSourceList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sourceEndPoint_sourceList of this SourceEndPointSourceList.  # noqa: E501
        :rtype: SourceEndPointSourceList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_id(self) -> str:
        """Gets the source_id of this SourceEndPointSourceList.


        :return: The source_id of this SourceEndPointSourceList.
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id: str):
        """Sets the source_id of this SourceEndPointSourceList.


        :param source_id: The source_id of this SourceEndPointSourceList.
        :type source_id: str
        """

        self._source_id = source_id

    @property
    def type(self) -> SourceType:
        """Gets the type of this SourceEndPointSourceList.


        :return: The type of this SourceEndPointSourceList.
        :rtype: SourceType
        """
        return self._type

    @type.setter
    def type(self, type: SourceType):
        """Sets the type of this SourceEndPointSourceList.


        :param type: The type of this SourceEndPointSourceList.
        :type type: SourceType
        """

        self._type = type

    @property
    def base_url(self) -> str:
        """Gets the base_url of this SourceEndPointSourceList.


        :return: The base_url of this SourceEndPointSourceList.
        :rtype: str
        """
        return self._base_url

    @base_url.setter
    def base_url(self, base_url: str):
        """Sets the base_url of this SourceEndPointSourceList.


        :param base_url: The base_url of this SourceEndPointSourceList.
        :type base_url: str
        """

        self._base_url = base_url

    @property
    def user(self) -> str:
        """Gets the user of this SourceEndPointSourceList.


        :return: The user of this SourceEndPointSourceList.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this SourceEndPointSourceList.


        :param user: The user of this SourceEndPointSourceList.
        :type user: str
        """

        self._user = user

    @property
    def _pass(self) -> str:
        """Gets the _pass of this SourceEndPointSourceList.


        :return: The _pass of this SourceEndPointSourceList.
        :rtype: str
        """
        return self.__pass

    @_pass.setter
    def _pass(self, _pass: str):
        """Sets the _pass of this SourceEndPointSourceList.


        :param _pass: The _pass of this SourceEndPointSourceList.
        :type _pass: str
        """

        self.__pass = _pass
