# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VehicleType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    TWOWHEELER = "TwoWheeler"
    THREEWHEELER = "ThreeWheeler"
    FOURWHEELER = "FourWheeler"
    HEAVYVEHICLE = "HeavyVehicle"
    CAR = "Car"
    MOTORBIKE = "Motorbike"
    MINI_TRUCK = "Mini-truck"
    VAN = "Van"
    CAR_TAXI = "Car-Taxi"
    BUS = "Bus"
    TUK_TUK = "Tuk-tuk"
    UNDETERMINED = "Undetermined"
    OTHER = "Other"
    def __init__(self):  # noqa: E501
        """VehicleType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'VehicleType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The vehicleType of this VehicleType.  # noqa: E501
        :rtype: VehicleType
        """
        return util.deserialize_model(dikt, cls)
